### ISSUE TITLE
Run detail - rename started/finished headings to created/updated

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/hyperdrive-trigger#213]
Run detail - started date/time is same for all entries.
Backend bug - started day time is set when instance entity is created. (Should be set when jobs is being executed)
![image](https://user-images.githubusercontent.com/54136196/84393821-60a8b980-abfc-11ea-9e89-3e6985409710.png)

**Comment by kevinwallimann** [comment]
I think there is some confusion here. Indeed, the started time is set on `JobInstance`, but that's exactly as intended, since the fields on `JobInstance` are `created` and `updated`. One could thus argue that the column headings are wrong. They should be "Created" and "Last updated".

One could argue that "Started" and "Finished" would be more useful, but in that case, I think these fields should be added to `JobInstance` rather than replace "Created" and "Updated"

**Comment by jozefbakus** [comment]
As discussed, we will rename started/finished headings to created/updated in this story.
