### ISSUE TITLE
BIGSERIAL NOT NULL

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/hyperdrive-trigger#26]
BIGSERIAL should include NOT NULL, does it? 
Required investigation.

**Comment by kevinwallimann** [comment]
I tested the following:
```
CREATE TABLE sensor5 (id BIGSERIAL);
INSERT INTO sensor5(id) VALUES (null);
```
giving me a not-null error

```
local2.public> INSERT INTO sensor5(id) VALUES (null)
[2020-02-28 16:33:03] [23502] ERROR: null value in column "id" violates not-null constraint
[2020-02-28 16:33:03] Detail: Failing row contains (null).
```

So, I'd conclude that `SERIAL` implicitly entails `NOT NULL`.

The same is true for `IDENTITY` which should be favoured over `SERIAL` now since the former is a SQL-Standard. See e.g. https://stackoverflow.com/questions/55300370/postgresql-serial-vs-identity

```
CREATE TABLE sensor3 (id BIGINT GENERATED BY DEFAULT AS IDENTITY);
INSERT INTO sensor3(id) VALUES (null);
```
gives a not-null constraint violation.
