### ISSUE TITLE
Run workflows - bulk

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/hyperdrive-trigger#450]
User should be able to manually trigger multiple workflows.

**Comment by kevinwallimann** [comment]
I think we should configure a maximum number of workflows that you can run at the same time

**Comment by jozefbakus** [comment]
I would rather limit this functionality by project.

**Comment by kevinwallimann** [comment]
I still feel a bit uneasy about this feature. It's too easy to run dozens of workflows.
- On the UI, I'd wish for some confirmation dialog. Since we have confirmation dialogs for almost all of the actions, the user will expect it on the bulk run as well.
- Such a confirmation box should make clear that there's no way to cancel workflows. In fact, this could be the next request
