### ISSUE TITLE
@Inject vs @Autowired

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/hyperdrive-trigger#51]
@Inject vs @Autowired

**Comment by kevinwallimann** [comment]
https://javarevisited.blogspot.com/2017/04/difference-between-autowired-and-inject-annotation-in-spring-framework.html

- @Inject is specified by JSR-330, @Autowired isn't
- Since Spring 3.0, both are supported
- @Autowired seems to be more popular, but that may be just because many projects started before Spring 3.0
=> I vote for @Inject

**Comment by kevinwallimann** [comment]
Closed because PR merged
